### PR TITLE
Update year, because its a new year.

### PR DESCRIPTION
**Pull request by dglloyd**
Yolo.

### CODE REVIEW

**Comment by kaleposhobios** [comment]
I'm not sure how I'm still allowed to access this but you should probably remove me. 😭

**Comment by tamentis** [comment]
That repo is public, even *I* have access to it \o/

**Comment by kaleposhobios** [comment]
Hah I didn't realize. Looks like it's the perfect place for our spy data drops.

**Comment by tamentis** [comment]
Here you go: 💾 💾 💾 💾 💾 💾. It's a big data drop this month.

**Comment by natronics** [comment]
👀

**Comment by Souloist** [comment]
👀

**Pull request merged**
